/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as DronesRouteImport } from './routes/drones'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DronesIndexRouteImport } from './routes/drones.index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DronesSlugRouteImport } from './routes/drones.$slug'
import { Route as CategoriasSlugRouteImport } from './routes/categorias.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesRoute = DronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesIndexRoute = DronesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DronesRoute,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const DronesSlugRoute = DronesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DronesRoute,
} as any)
const CategoriasSlugRoute = CategoriasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriasRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/drones': typeof DronesRouteWithChildren
  '/marcas': typeof MarcasRoute
  '/nosotros': typeof NosotrosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/drones/$slug': typeof DronesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/drones/': typeof DronesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/marcas': typeof MarcasRoute
  '/nosotros': typeof NosotrosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/drones/$slug': typeof DronesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/categorias': typeof CategoriasIndexRoute
  '/drones': typeof DronesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/drones': typeof DronesRouteWithChildren
  '/marcas': typeof MarcasRoute
  '/nosotros': typeof NosotrosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/categorias/$slug': typeof CategoriasSlugRoute
  '/drones/$slug': typeof DronesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/drones/': typeof DronesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contacto'
    | '/drones'
    | '/marcas'
    | '/nosotros'
    | '/blog/$slug'
    | '/categorias/$slug'
    | '/drones/$slug'
    | '/blog/'
    | '/categorias/'
    | '/drones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/marcas'
    | '/nosotros'
    | '/blog/$slug'
    | '/categorias/$slug'
    | '/drones/$slug'
    | '/blog'
    | '/categorias'
    | '/drones'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contacto'
    | '/drones'
    | '/marcas'
    | '/nosotros'
    | '/blog/$slug'
    | '/categorias/$slug'
    | '/drones/$slug'
    | '/blog/'
    | '/categorias/'
    | '/drones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  DronesRoute: typeof DronesRouteWithChildren
  MarcasRoute: typeof MarcasRoute
  NosotrosRoute: typeof NosotrosRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones': {
      id: '/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof DronesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones/': {
      id: '/drones/'
      path: '/'
      fullPath: '/drones/'
      preLoaderRoute: typeof DronesIndexRouteImport
      parentRoute: typeof DronesRoute
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/drones/$slug': {
      id: '/drones/$slug'
      path: '/$slug'
      fullPath: '/drones/$slug'
      preLoaderRoute: typeof DronesSlugRouteImport
      parentRoute: typeof DronesRoute
    }
    '/categorias/$slug': {
      id: '/categorias/$slug'
      path: '/$slug'
      fullPath: '/categorias/$slug'
      preLoaderRoute: typeof CategoriasSlugRouteImport
      parentRoute: typeof CategoriasRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DronesRouteChildren {
  DronesSlugRoute: typeof DronesSlugRoute
  DronesIndexRoute: typeof DronesIndexRoute
}

const DronesRouteChildren: DronesRouteChildren = {
  DronesSlugRoute: DronesSlugRoute,
  DronesIndexRoute: DronesIndexRoute,
}

const DronesRouteWithChildren =
  DronesRoute._addFileChildren(DronesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactoRoute: ContactoRoute,
  DronesRoute: DronesRouteWithChildren,
  MarcasRoute: MarcasRoute,
  NosotrosRoute: NosotrosRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
