/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as DronesTopografiaRouteImport } from './routes/drones-topografia'
import { Route as DronesSeguridadRouteImport } from './routes/drones-seguridad'
import { Route as DronesOilGasRouteImport } from './routes/drones-oil-gas'
import { Route as DronesMineriaRouteImport } from './routes/drones-mineria'
import { Route as DronesAgriculturaRouteImport } from './routes/drones-agricultura'
import { Route as DronesRouteImport } from './routes/drones'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DronesIndexRouteImport } from './routes/drones.index'
import { Route as CategoriasIndexRouteImport } from './routes/categorias.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DronesSlugRouteImport } from './routes/drones.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesTopografiaRoute = DronesTopografiaRouteImport.update({
  id: '/drones-topografia',
  path: '/drones-topografia',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesSeguridadRoute = DronesSeguridadRouteImport.update({
  id: '/drones-seguridad',
  path: '/drones-seguridad',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesOilGasRoute = DronesOilGasRouteImport.update({
  id: '/drones-oil-gas',
  path: '/drones-oil-gas',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesMineriaRoute = DronesMineriaRouteImport.update({
  id: '/drones-mineria',
  path: '/drones-mineria',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesAgriculturaRoute = DronesAgriculturaRouteImport.update({
  id: '/drones-agricultura',
  path: '/drones-agricultura',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesRoute = DronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesIndexRoute = DronesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DronesRoute,
} as any)
const CategoriasIndexRoute = CategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DronesSlugRoute = DronesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DronesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/drones': typeof DronesRouteWithChildren
  '/drones-agricultura': typeof DronesAgriculturaRoute
  '/drones-mineria': typeof DronesMineriaRoute
  '/drones-oil-gas': typeof DronesOilGasRoute
  '/drones-seguridad': typeof DronesSeguridadRoute
  '/drones-topografia': typeof DronesTopografiaRoute
  '/marcas': typeof MarcasRoute
  '/nosotros': typeof NosotrosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/drones/$slug': typeof DronesSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/blog/': typeof BlogIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/drones/': typeof DronesIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/drones-agricultura': typeof DronesAgriculturaRoute
  '/drones-mineria': typeof DronesMineriaRoute
  '/drones-oil-gas': typeof DronesOilGasRoute
  '/drones-seguridad': typeof DronesSeguridadRoute
  '/drones-topografia': typeof DronesTopografiaRoute
  '/marcas': typeof MarcasRoute
  '/nosotros': typeof NosotrosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/drones/$slug': typeof DronesSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/blog': typeof BlogIndexRoute
  '/categorias': typeof CategoriasIndexRoute
  '/drones': typeof DronesIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/drones': typeof DronesRouteWithChildren
  '/drones-agricultura': typeof DronesAgriculturaRoute
  '/drones-mineria': typeof DronesMineriaRoute
  '/drones-oil-gas': typeof DronesOilGasRoute
  '/drones-seguridad': typeof DronesSeguridadRoute
  '/drones-topografia': typeof DronesTopografiaRoute
  '/marcas': typeof MarcasRoute
  '/nosotros': typeof NosotrosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/drones/$slug': typeof DronesSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/blog/': typeof BlogIndexRoute
  '/categorias/': typeof CategoriasIndexRoute
  '/drones/': typeof DronesIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contacto'
    | '/drones'
    | '/drones-agricultura'
    | '/drones-mineria'
    | '/drones-oil-gas'
    | '/drones-seguridad'
    | '/drones-topografia'
    | '/marcas'
    | '/nosotros'
    | '/blog/$slug'
    | '/drones/$slug'
    | '/email/unsubscribe'
    | '/blog/'
    | '/categorias/'
    | '/drones/'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/drones-agricultura'
    | '/drones-mineria'
    | '/drones-oil-gas'
    | '/drones-seguridad'
    | '/drones-topografia'
    | '/marcas'
    | '/nosotros'
    | '/blog/$slug'
    | '/drones/$slug'
    | '/email/unsubscribe'
    | '/blog'
    | '/categorias'
    | '/drones'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contacto'
    | '/drones'
    | '/drones-agricultura'
    | '/drones-mineria'
    | '/drones-oil-gas'
    | '/drones-seguridad'
    | '/drones-topografia'
    | '/marcas'
    | '/nosotros'
    | '/blog/$slug'
    | '/drones/$slug'
    | '/email/unsubscribe'
    | '/blog/'
    | '/categorias/'
    | '/drones/'
    | '/api/public/contact'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  DronesRoute: typeof DronesRouteWithChildren
  DronesAgriculturaRoute: typeof DronesAgriculturaRoute
  DronesMineriaRoute: typeof DronesMineriaRoute
  DronesOilGasRoute: typeof DronesOilGasRoute
  DronesSeguridadRoute: typeof DronesSeguridadRoute
  DronesTopografiaRoute: typeof DronesTopografiaRoute
  MarcasRoute: typeof MarcasRoute
  NosotrosRoute: typeof NosotrosRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  CategoriasIndexRoute: typeof CategoriasIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones-topografia': {
      id: '/drones-topografia'
      path: '/drones-topografia'
      fullPath: '/drones-topografia'
      preLoaderRoute: typeof DronesTopografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones-seguridad': {
      id: '/drones-seguridad'
      path: '/drones-seguridad'
      fullPath: '/drones-seguridad'
      preLoaderRoute: typeof DronesSeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones-oil-gas': {
      id: '/drones-oil-gas'
      path: '/drones-oil-gas'
      fullPath: '/drones-oil-gas'
      preLoaderRoute: typeof DronesOilGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones-mineria': {
      id: '/drones-mineria'
      path: '/drones-mineria'
      fullPath: '/drones-mineria'
      preLoaderRoute: typeof DronesMineriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones-agricultura': {
      id: '/drones-agricultura'
      path: '/drones-agricultura'
      fullPath: '/drones-agricultura'
      preLoaderRoute: typeof DronesAgriculturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones': {
      id: '/drones'
      path: '/drones'
      fullPath: '/drones'
      preLoaderRoute: typeof DronesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones/': {
      id: '/drones/'
      path: '/'
      fullPath: '/drones/'
      preLoaderRoute: typeof DronesIndexRouteImport
      parentRoute: typeof DronesRoute
    }
    '/categorias/': {
      id: '/categorias/'
      path: '/categorias'
      fullPath: '/categorias/'
      preLoaderRoute: typeof CategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drones/$slug': {
      id: '/drones/$slug'
      path: '/$slug'
      fullPath: '/drones/$slug'
      preLoaderRoute: typeof DronesSlugRouteImport
      parentRoute: typeof DronesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DronesRouteChildren {
  DronesSlugRoute: typeof DronesSlugRoute
  DronesIndexRoute: typeof DronesIndexRoute
}

const DronesRouteChildren: DronesRouteChildren = {
  DronesSlugRoute: DronesSlugRoute,
  DronesIndexRoute: DronesIndexRoute,
}

const DronesRouteWithChildren =
  DronesRoute._addFileChildren(DronesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactoRoute: ContactoRoute,
  DronesRoute: DronesRouteWithChildren,
  DronesAgriculturaRoute: DronesAgriculturaRoute,
  DronesMineriaRoute: DronesMineriaRoute,
  DronesOilGasRoute: DronesOilGasRoute,
  DronesSeguridadRoute: DronesSeguridadRoute,
  DronesTopografiaRoute: DronesTopografiaRoute,
  MarcasRoute: MarcasRoute,
  NosotrosRoute: NosotrosRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  CategoriasIndexRoute: CategoriasIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
